POST http://localhost:8080/auth/login/seller
  Content-Type: application/json

  {
    "Id": "3442f8959a84dea7ee197c632cb2df15",
    "password": "password"
  }

### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDQyZjg5NTlhODRkZWE3ZWUxOTdjNjMyY2IyZGYxNSIsImp0aSI6ImI0ZDU2NDY5LTM1Y2QtNDczNy05ZDRjLTVmNDAzYjU3MjVjOCIsInVzZXJfaWQiOiIzNDQyZjg5NTlhODRkZWE3ZWUxOTdjNjMyY2IyZGYxNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InNlbGxlciIsImV4cCI6MTc3NzQ1NTAwOSwiaXNzIjoiY2xvdWQtbmF0aXZlLXNob3AiLCJhdWQiOiJjbG91ZC1uYXRpdmUtc2hvcC1jbGllbnRzIn0.zrVQQZv_tzPwqfEEgTEoqWP815ikGgja68wYftwNHyw
####

GET http://localhost:8080/order/seller
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDQyZjg5NTlhODRkZWE3ZWUxOTdjNjMyY2IyZGYxNSIsImp0aSI6IjBhODFmYTg0LWM1NDItNGY5NC1hYzk0LTc2MTI2NzIwOTE3MiIsInVzZXJfaWQiOiIzNDQyZjg5NTlhODRkZWE3ZWUxOTdjNjMyY2IyZGYxNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InNlbGxlciIsImV4cCI6MTc3NzQ1NTI5MywiaXNzIjoiY2xvdWQtbmF0aXZlLXNob3AiLCJhdWQiOiJjbG91ZC1uYXRpdmUtc2hvcC1jbGllbnRzIn0.s2dsHoYJvHV940pAij5C1eWmsXwMlF2uLEIC_lup00Q
###

GET http://localhost:8080/order/seller/bc8a5de6abf5b14f98a6135a7fb46731
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDQyZjg5NTlhODRkZWE3ZWUxOTdjNjMyY2IyZGYxNSIsImp0aSI6IjBhODFmYTg0LWM1NDItNGY5NC1hYzk0LTc2MTI2NzIwOTE3MiIsInVzZXJfaWQiOiIzNDQyZjg5NTlhODRkZWE3ZWUxOTdjNjMyY2IyZGYxNSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InNlbGxlciIsImV4cCI6MTc3NzQ1NTI5MywiaXNzIjoiY2xvdWQtbmF0aXZlLXNob3AiLCJhdWQiOiJjbG91ZC1uYXRpdmUtc2hvcC1jbGllbnRzIn0.s2dsHoYJvHV940pAij5C1eWmsXwMlF2uLEIC_lup00Q
###

POST http://localhost:8080/order
  Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjM2OGNhMGY1NmQ0NjMyZjQ0ZDU4Y2E0MzE0ODdiMiIsImp0aSI6IjdhZThmZGFhLTg4NmEtNDQxMC05ZGE5LTQ2MDVhNmVkMDFhYSIsInVzZXJfaWQiOiJiNjM2OGNhMGY1NmQ0NjMyZjQ0ZDU4Y2E0MzE0ODdiMiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6ImN1c3RvbWVyIiwiZXhwIjoxNzc2OTQ2NTg0LCJpc3MiOiJjbG91ZC1uYXRpdmUtc2hvcCIsImF1ZCI6ImNsb3VkLW5hdGl2ZS1zaG9wLWNsaWVudHMifQ.DnwkDMJXfmCXT1LRcn1Uib8VYvAIaPjFu07yzFwCPd8
  Content-Type: application/json

  {
  "items": [
    {
      "productId": "1e9e8ef04dbcff4541ed26657ea517e5",
      "sellerId": "3442f8959a84dea7ee197c632cb2df15",
      "quantity": 1,
      "price": 1000
    }
  ]
}